---
- shell: "ls -1 {{ vsftpd_local_root }}/{{ item.username }}"
  register: contents

- set_fact:
    managed: "{{ managed | default([]) + [ inner_item.path ] }}"
  with_items: "{{ item.bindpath }}"
  loop_control:
    loop_var: inner_item

- debug: msg="{{ vsftpd_local_root }}/{{ item.username }}/{{ inner_item | realpath | basename }}" verbosity=3
  with_items: "{{ contents.stdout_lines }}"
  when: inner_item not in "{{ managed }}"
  loop_control:
    loop_var: inner_item

- name: Unbind unmanaged paths - unmounted
  mount:
    opts: bind
    fstype: none
    state: unmounted
    name: "{{ vsftpd_local_root }}/{{ item.username }}/{{ inner_item | realpath | basename }}"
  with_items: "{{ contents.stdout_lines }}"
  when: inner_item not in "{{ managed }}"
  loop_control:
    loop_var: inner_item

- name: Unbind unmanaged paths - absent
  mount:
    opts: bind
    fstype: none
    state: absent
    name: "{{ vsftpd_local_root }}/{{ item.username }}/{{ inner_item | realpath | basename }}"
  with_items: "{{ contents.stdout_lines }}"
  when: inner_item not in "{{ managed }}"
  loop_control:
    loop_var: inner_item
